platform :ios, '8.0'

use_frameworks!

target ‘KSPersonalFinance’ do
pod 'MagicalRecord'
pod 'DGActivityIndicatorView'
pod 'FSCalendar'
pod 'NSDate+Calendar'
pod 'HSDatePickerViewController', '~> 1.0'
pod 'HMSegmentedControl'
pod 'Charts'

end

